version: 0.2

phases:
  install:
    commands:
      - npm install -g @angular/cli
      - cd ng-spa
      - echo Installing node modules...
      - npm install
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=003966880635.dkr.ecr.us-east-1.amazonaws.com/ng-spa
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - ng build --prod
      - pwd 
      - ls -la ./dist/
      #- ls -la ./dist/ng-spa
      #- ls -la ./dist/ng-site
      - echo Building the Docker image...          
      - docker build . -t $REPOSITORY_URI:latest  
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      - docker run --rm $REPOSITORY_URI:latest ls -la /usr/share/nginx/html

  post_build:
    commands:
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"ng-spa","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - ls -ltr
artifacts:
    files: ./ng-spa/imagedefinitions.json
    discard-paths: true