apiVersion: v1
kind: DeploymentConfig
metadata:
  name: ng-spa
  labels:
    name: ng-spa
    app: ng-spa
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: ng-spa
    spec:
      containers:
      - name: ng-spa
        image: ricardojudo/ng-spa:latest
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 1
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /var/cache/nginx
          name: ng-spa-volume1
        - mountPath: /var/run
          name: ng-spa-volume2
      volumes:
      - name: ng-spa-volume1
        emptyDir: {}
      - name: ng-spa-volume2
        emptyDir: {}
      triggers:
      - type: ConfigChange
---
apiVersion: v1
kind: Service
metadata:
  name: ng-spa
  labels:
    name: ng-spa
    app: ng-spa
spec:
  ports:
    # the port that this service should serve on
  - port: 8080
    targetPort: 8080
  selector:
    name: ng-spa
--- 
apiVersion: v1
kind: Route
metadata:
  name: ng-spa
  app: ng-spa
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: ng-spa
