#
# https://strimzi.io/
#
# Download installation files 
# wget https://github.com/strimzi/strimzi-kafka-operator/releases/download/0.11.0/strimzi-0.11.0.tar.gz
#
# Install as cluster-admin
# oc login -u system:admin
#
# 
# 
# sed -i 's/namespace: .*/namespace: v4-0/' install/cluster-operator/*RoleBinding*.yaml
# oc apply -f install/cluster-operator -n v4-0
# oc apply -f examples/templates/cluster-operator -n v4-0
# oc apply -f install/strimzi-admin
# oc adm policy add-cluster-role-to-user strimzi-admin developer
#
#
# As developer
# oc login -u developer
# oc apply -f kafka.yml 

apiVersion: kafka.strimzi.io/v1alpha1
kind: Kafka
metadata:
  name: kafka
spec:
  kafka:
    version: 2.1.0
    replicas: 1
    listeners:
      plain: {}
      tls: {}
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.1"
    storage:
      type: ephemeral
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
userOperator: {}