apiVersion: v1
kind: DeploymentConfig
metadata:
  name: events-log-db
  labels:
    name: events-log-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: events-log-db
    spec:
      containers:
      - name: events-log-db
        image: mariadb:10.2
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: my-secret-pw
          - name: MYSQL_DATABASE
            value: events_db
        ports:
        - name: mysql
          containerPort: 3306
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 15
          timeoutSeconds: 1
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 15
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: events-log-db-volume
          
      volumes:
      - name: events-log-db-volume
        emptyDir: {}
      triggers:
      - type: ConfigChange
---
apiVersion: v1
kind: Service
metadata:
  name: events-log-db
  labels:
    name: events-log-db
spec:
  ports:
    # the port that this service should serve on
  - port: 3306
    targetPort: 3306
  selector:
    name: events-log-db