apiVersion: v1
kind: DeploymentConfig
metadata:
  name: events-channel
  labels:
    name: events-channel
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: events-channel
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.7.14-alpine
        ports:
        - containerPort: 5672
        
        #securityContext:
        #  capabilities:
        #    drop:
        #      - all
        #    add:
        #      - CHOWN
        #      - SETGID
        #      - SETUID
        #      - DAC_OVERRIDE
        #  readOnlyRootFilesystem: true
      nodeSelector:
beta.kubernetes.io/os: linux

---
apiVersion: v1
kind: Service
metadata:
  name: events-channel
  labels:
    name: events-channel
spec:
  ports:
    # the port that this service should serve on
  - port: 5672
    targetPort: 5672
  selector:
    name: events-channel